pipeline:
  name: mycicdpipeline
  identifier: mycicdpipeline
  projectIdentifier: myapp
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: mygithubconnector
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: myk8connector
              namespace: build
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildandPushMyApp
                  identifier: BuildandPushMyApp
                  spec:
                    connectorRef: mydockerhubconnector
                    repo: nicklotz/myapp
                    tags:
                      - <+pipeline.variables.buildVersion>
    - stage:
        name: prod deploy
        identifier: prod_deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: myapp
          environment:
            environmentRef: prod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: myprodinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: buildVersion
      type: String
      description: ""
      required: true
      value: <+input>
  allowStageExecutions: true
