pipeline:
  name: mycicdpipeline
  identifier: mycicdpipeline
  projectIdentifier: myapp
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: mygithubconnector
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: myk8connector
              namespace: build
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildandPushMyApp
                  identifier: BuildandPushMyApp
                  spec:
                    connectorRef: mydockerhubconnector
                    repo: nicklotz/myapp
                    tags:
                      - <+pipeline.variables.buildVersion>
    - stage:
        name: prod
        identifier: prod
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          gitOpsEnabled: true
          service:
            serviceRef: myappservice
          execution:
            steps:
              - step:
                  type: UpdateGitOpsApp
                  name: UpdateGitOpsApp_1
                  identifier: UpdateGitOpsApp_1
                  spec:
                    targetRevision: main
                    helm:
                      valueFiles:
                        - values.yaml
                      parameters:
                        - name: replicaCount
                          value: "5"
                      fileParameters: []
                    applicationName: myapp
                    agentId: mygitopsagent
                  timeout: 10m
            rollbackSteps: []
          environment:
            environmentRef: prod
            deployToAll: false
            gitOpsClusters:
              - identifier: mygitonpscluster
                agentIdentifier: mygitopsagent
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: buildVersion
      type: String
      description: ""
      required: true
      value: <+input>
  allowStageExecutions: true
